### ISSUE TITLE
 duplicate_classes errors - Project with path ':react-native-jitsimeet' could not be found in project ':app'.

### ISSUE THREAD

**Issue by aaryavrate** [bortolilucas/react-native-jitsimeet#12]
I am trying to follow Troubleshoot steps for duplicate classes.
But I get this error: 
`
Project with path ':react-native-jitsimeet' could not be found in project ':app'.

`

The Readme mentions no other step. Can someone please guide?

**Comment by rcidt** [comment]
@aaryavrate you can only define the room name (aka subject) on start up.

In your url, add the following parameters: `config.hideConferenceSubject=false` and `config.subject="Room Name"`

For example: 
```
https://jitsi.com/roomId?config.hideConferenceSubject=false&config.subject="Room Name"
```
_**Note** be mindful of the double quotes around the room name string._

Also, make sure you have the `meeting-name.enabled` feature flag set to `true`.
