### ISSUE TITLE
App Release Build Crash 

### ISSUE THREAD

**Issue by riyas145** [bortolilucas/react-native-jitsimeet#14]
App Crash after release build when open app immediately  closed and not able to get crash build 

"dependencies": {
    "@bortolilucas/react-native-jitsimeet": "^2.0.2",
    "@react-native-async-storage/async-storage": "^1.15.15",
    "@react-native-community/slider": "^4.2.0",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^5.5.1",
    "axios": "^0.26.0",
    "formik": "^2.2.9",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-date-picker": "^4.1.3",
    "react-native-document-picker": "^8.0.0",
    "react-native-fbsdk-next": "^7.0.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-orientation-locker": "^1.4.0",
    "react-native-pager-view": "^5.4.11",
    "react-native-paper": "^4.11.2",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.9.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^3.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-simple-toast": "^1.1.3",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-video": "^5.2.0",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "yup": "^0.32.11"
  },

**Comment by SabinSursa** [comment]
same here, any hints sir, :)

**Comment by riyas145** [comment]
install latest version 
and add this inside  app/build.gradle
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
    enableHermes: false,  // clean and rebuild if changing
]
indside dependencies (app/build.gradle)
    implementation ('org.jitsi.react:jitsi-meet-sdk:+') { transitive = true
     exclude group: 'com.facebook.react',module:'react-native-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-reanimated'
        exclude group: 'com.facebook.react',module:'react-native-gesture-handler'
        exclude group: 'com.facebook.react',module:'react-native-slider'
        exclude group: 'com.facebook.react',module:'react-native-screens'
        exclude group: 'com.facebook.react',module:'react-native-safe-area-context'
        exclude group: 'com.facebook.react',module:'react-native-video'
        exclude group: 'com.facebook.react',module:'react-native-google-signin'
        exclude group: 'com.facebook.react',module:'react-native-vector-icons'
     }
    implementation(project(':bortolilucas_react-native-jitsimeet')) {
        exclude group: 'com.facebook.react',module:'react-native-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-reanimated'
        exclude group: 'com.facebook.react',module:'react-native-gesture-handler'
        exclude group: 'com.facebook.react',module:'react-native-slider'
        exclude group: 'com.facebook.react',module:'react-native-screens'
        exclude group: 'com.facebook.react',module:'react-native-safe-area-context'
        exclude group: 'com.facebook.react',module:'react-native-video'
        exclude group: 'com.facebook.react',module:'react-native-vector-icons'
    }

**Comment by bortolilucas** [comment]
I think the issue is having hermes enabled. I had the same issue and solved by disabling hermes. I'm not sure why but JitsiMeetSDK crashs in release with hermes

**Comment by riyas145** [comment]
yes im also fixed by disable Hermes thanks @bortolilucas

**Comment by riyas145** [comment]
@bortolilucas  can u build own maven repo for jitsi ? i have build that but i don't know how upload that into the repository if we host that we can run jitsi using RN 66 Version @bortolilucas

**Comment by riyas145** [comment]
@bortolilucas  **https://github.com/riyas145/jitsi-maven-new** here i pushed jitsi new maven with 0.66 react native version

**Comment by jplandry908** [comment]
It looks like v5+ is already using RN 0.66.4?

https://github.com/jitsi/jitsi-maven-repository/blob/master/releases/org/jitsi/react/jitsi-meet-sdk/5.0.0/jitsi-meet-sdk-5.0.0.pom
