### ISSUE TITLE
is there new feature in the future to hide/show controls on native UI (chat,share,etc...)

### ISSUE THREAD

**Issue by MinaSamir11** [bortolilucas/react-native-jitsimeet#19]
- need to control some button on native, while call launchJitsiMeetView.

**Comment by bortolilucas** [comment]
You can pass an object with feature flags in options for this purpose.

Take a look at the usage section
https://github.com/bortolilucas/react-native-jitsimeet#usage

For example, you can pass this flag to hide the chat button:
```js
JitsiMeet.launchJitsiMeetView({
  room: 'ReactNativeJitsiRoom',
  userInfo: {
    displayName: 'React Native Jitsi Meet Example',
    email: 'example@test.com',
    avatar: 'https://picsum.photos/200',
  },
  featureFlags: {
    'chat.enabled': false,
  },
})
```

Here is the list with all feature-flags
https://jitsi.github.io/handbook/docs/dev-guide/mobile-feature-flags/

**Comment by MinaSamir11** [comment]
awesome, thanks
