### ISSUE TITLE
Implement audio/video muted conference options

### ISSUE THREAD

**Issue by teddyesky** [bortolilucas/react-native-jitsimeet#24]
Hey there, 

I'm switching over from https://github.com/skrafft/react-native-jitsi-meet and noticed that this wrapper doesn't have the audioMuted/videoMuted options when the conference is launched. Would it be possible to add that? Thanks!

**Comment by bortolilucas** [comment]
@teddyesky My MacBook went dead so I am unable to build iOS apps at the moment. As soon as I have it figured out, I'll gladly implement it.

But if it is urgent, you could open a PR.

**Comment by bortolilucas** [comment]
Thanks for the PR, I'll soon merge it

**Comment by socialcode-rob1** [comment]
Trying this on 2.3.0, using Mode 1 and the camera seems to still be activated when the call starts.

I'm passing videoMuted into the conference options...

```
    const conferenceOptions = {
      ...
      videoMuted: true,
    };
    
    JitsiMeet.launchJitsiMeetView(conferenceOptions);
```
