### ISSUE TITLE
[Bug]: RNGestureHandlerModule.attachGestureHandler got 2 arguments, expected 3

### ISSUE THREAD

**Issue by socialcode-rob1** [bortolilucas/react-native-jitsimeet#27]
## Description
After upgrading `minSdkVersion` from 23 to 24 to support this lib it no longer meets `react-native-gesture-handler` function signature.  

You can't upgrade `react-native-gesture-handler` because this package won't support it.

**Has anyone made this package work with react-navigation?**

```
RNGestureHandlerModule.attachGestureHandler got 2 arguments, expected 3
...
 ```
 
 ### Screenshots
![image](https://user-images.githubusercontent.com/540616/163821331-b18e31ff-ae34-4296-bc60-5ae040a25d72.png)

 ## Steps To Reproduce
 1. add packages according to instructions
 2. run application
 
 ## Package versions
package.json
```
...
 "dependencies": {
    "@bortolilucas/react-native-jitsimeet": "^2.1.2",  
    "@react-native-community/masked-view": "0.1.11",
    "@react-navigation/drawer": "^5.x",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "^5.x",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "1.10.3",
    "react-native-reanimated": "1.13.1",
    "react-native-screens": "2.18.1",
    ...
  },
...
```

build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlinVersion = "1.3.72"
        ndkVersion = "21.4.7075529"
    }
...
```

**Comment by socialcode-rob1** [comment]
so far I got the app building and running by...

1. upgrading to RN 66.4 and all that goes with it.
2. downgrade this package to 2.0.2 because 2.1.x uses a newer version of jitsi-sdk that forces compileSdkVersion to 31 which breaks a bunch of other stuff

Running some tests on experience.  I may need to branch from the older version of this package and re-apply updates.

**Comment by socialcode-rob1** [comment]
In this state the buttons don't work likely due to this issue 
`E/JitsiMeetSDK: [features/app] Error(TypeError){"message":"h.playTouchSound is not a function.`

More info 
https://github.com/jitsi/jitsi-meet/issues/8948#issuecomment-856566676

**Comment by bortolilucas** [comment]
@socialcode-rob1 I didn´t understand it. Do you have any suggestion to fix the problem?

**Comment by socialcode-rob1** [comment]
In my case (using 2.0,2 of this lib), I need to figure out which version of RN is being referenced in `org.jitsi.react:jitsi-meet-sdk:4.1.0`. Then attempt to patch the RN Touchable.js and rebuild the the jitsi-meet dependency.

That's all i can think of right now.  It's like a game of groundhog whacking between the RN lib, Jitsi SDK, RNJitsiMeet lib compatibility & versions.

**Comment by socialcode-rob1** [comment]
i should probably create a new issue, since I've moved away from this one.

**Comment by socialcode-rob1** [comment]
For completeness, how I ended up fixing my issue...

upgraded a few packages...
...
 "dependencies": {
    "@bortolilucas/react-native-jitsimeet": "^2.1.2",  
    "@react-native-community/masked-view": "0.1.11",
    "@react-navigation/drawer": "^5.x",
    "@react-navigation/native": "5.9.4",
    "@react-navigation/stack": "^5.x",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-gesture-handler": "2.1.0",
    "react-native-reanimated": "1.13.1",
    "react-native-screens": "2.18.1",
    ...
  },
...

patched react-native-gesture-handler...

react-native-gesture-handler+2.1.0.patch
```javascription
diff --git a/node_modules/react-native-gesture-handler/android/build.gradle b/node_modules/react-native-gesture-handler/android/build.gradle
index 8afc3d5..4b1f721 100644
--- a/node_modules/react-native-gesture-handler/android/build.gradle
+++ b/node_modules/react-native-gesture-handler/android/build.gradle
@@ -26,7 +26,7 @@ def shouldUseCommonInterfaceFromReanimated() {
         def json = new JsonSlurper().parseText(inputFile.text)
         def reanimatedVersion = json.version as String
         def (major, minor, patch) = reanimatedVersion.tokenize('.')
-        return Integer.parseInt(minor) >= 3
+        return Integer.parseInt(major) >= 2 && Integer.parseInt(minor) >= 3
     } else {
         return false
     }
```

managed my implementation package due to conflicts with RN
```
defaultConfig {
      ...
        configurations.all {
          resolutionStrategy { 
            force 'androidx.fragment:fragment:1.3.6'
         }
      }
    }
```
