### ISSUE TITLE
Error compile swift source files (arm64)

### ISSUE THREAD

**Issue by ashankaushalya97** [bortolilucas/react-native-jitsimeet#3]
<img width="897" alt="Screenshot 2021-11-12 at 1 35 31 PM" src="https://user-images.githubusercontent.com/45938393/141432509-2acc2a4a-1ba2-4412-b80a-2507598a67be.png">

Getting swift compile issue while archiving the build. any solutions? @bortolilucas

**Comment by bortolilucas** [comment]
Hi @ashankaushalya97. Did you change your iOS version to `>=11.0` in both Xcode and podfile? It's important they have the same version
