### ISSUE TITLE
How to end Active Call ? or previous call

### ISSUE THREAD

**Issue by riyas145** [bortolilucas/react-native-jitsimeet#6]

**Comment by rcidt** [comment]
This is not currently implemented in this wrapper. But it is something that would be useful to have

I will submit a PR in the coming weeks to add this feature, stay tuned.

**Comment by rcidt** [comment]
Work has been done in #13

**Comment by riyas145** [comment]
@rcidt  are able to make release build? Pls tell me i was getting error and my app.was getting crash after build

**Comment by MinaSamir11** [comment]
@rcidt  
I got this error in build 
@objc func hangUp() {
   self.vc?.jitsiMeetView?.hangUp()
}

Value of type 'JitsiMeetViewController' has no member 'jitsiMeetView'
